# Generated by Django 6.0 on 2025-12-30 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_council_id', models.CharField(max_length=50, unique=True)),
                ('experience', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=10)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('court_appearance_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField()),
                ('languages', models.CharField(help_text='Comma separated languages', max_length=200)),
                ('education', models.TextField()),
                ('certifications', models.TextField(blank=True)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_cases', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_profile', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(related_name='advocates', to='advocates.specialization')),
            ],
            options={
                'ordering': ['-rating', '-total_cases'],
            },
        ),
        migrations.CreateModel(
            name='AdvocateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Bar Council License'), ('certificate', 'Certificate'), ('degree', 'Degree'), ('other', 'Other')], max_length=50)),
                ('document', models.FileField(upload_to='advocate_docs/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='advocates.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='AdvocateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='advocates.advocate')),
            ],
            options={
                'verbose_name_plural': 'Advocate Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('advocate', 'day_of_week', 'start_time')},
            },
        ),
    ]
